### ISSUE TITLE
No module named 'skvideo'

### ISSUE THREAD

**Issue by hempires47** [Filarius/video2video#1]
tried to use video2video script in the auto1111 webui and get hit with the following error upon attempting generation.
both FFMpeg and sk-video are installed, any ideas?

> Error completing request
Arguments: ('task(ic8vthr74fyadk4)', 0, 'make this a marble statue', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x1D4041723E0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 1.5, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 456, 810, 0, 0, 32, 0, '', '', '', [], 13, True, 'keyword prompt', 'keyword1, keyword2', 'None', 'textual inversion first', 'None', '0.7', 'None', True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 'x264', 'mci', 10, 5, False, True, True, True, 'intermediate', 'animation', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, True, -1.0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, 8, True, True, 16, 'PNN', True, True, True, '', False, 1, 'Both ▦', False, '', False, True, False, False, False, False, 0, False, '', '', '', 'generateMasksTab', 1, 4, 2.5, 30, 1.03, 1, 1, 5, 0.5, 5, False, True, True, True, True, 0, 'None', False, 0, 2, 512, 512, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2, '', 24, <tempfile._TemporaryFileWrapper object at 0x000001D40D1ED5D0>, 0.2, 1, True, True) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "F:\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "F:\stable-diffusion-webui\extensions\video2video\scripts\vid2vid.py", line 128, in run
    import skvideo
ModuleNotFoundError: No module named 'skvideo'

**Comment by Filarius** [comment]
pip install sk-video

**Comment by hempires47** [comment]
yeah sk-video is installed, the error persists though.

I'm assuming I'm making a pretty silly mistake somewhere lol

**Comment by Filarius** [comment]
If you set VENV in A1111 then maybe you install sk-video in wrong place. 
Then you need install from `venv/scripts/activate`
I made dirty fix to make sk-video be installed on A1111 start.

**Comment by hempires47** [comment]
did a pip uninstall along with a git pull to update the extension, it did install successfully upon reboot but it's now giving a new error

>Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "F:\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "F:\stable-diffusion-webui\extensions\video2video\scripts\vid2vid.py", line 148, in run
    skvideo.setFFmpegPath(os.path.join(path, "ffmpeg"))
UnboundLocalError: local variable 'skvideo' referenced before assignment

**Comment by Filarius** [comment]
New commit, please check.

**Comment by hempires47** [comment]
all seems to be working! thank you!
